### ISSUE TITLE
Edit course screen date picker displays incorrect days of the week

### ISSUE THREAD

**Issue by aaronstine** [13gne/shcoderdojo#15]
The day of the week is incorrect in the date picker. The date is correct but the day of the week is not. In the screenshot below, March 31 2017 _shoud_ be a **Friday**

![screen shot 2017-03-31 at 4 27 40 pm](https://cloud.githubusercontent.com/assets/22802722/24568204/0b768138-162f-11e7-921f-ab0a104a55b9.png)

**Comment by moottoast** [comment]
Wow. That's weird.

**Comment by aaronstine** [comment]
Yeah, it still fills in the correct date you pick so not a huge problem. But I agree, it's weird.

**Comment by moottoast** [comment]
Appears to be Safari only. Chrome and Firefox do not have the same symptom. Updating the js library for Flatpickr.
