### ISSUE TITLE
Consider creating new link on home screen for Path of the Ninja information or add to about

### ISSUE THREAD

**Issue by NovaG8r** [13gne/shcoderdojo#27]
A & I think we really need to get the whole new Path of the Ninja information on the website.  With pics of the Path, folders, lariats, bags, etc. as well as explanations of the program.  Hoping we can collaborate on where to put it and who provides what.  Will also send email to Aaron about it but would like it done asap.

**Comment by NovaG8r** [comment]
I believe we determined that the Path of the Ninja info should go right on the Home page of the website.  I know Aaron has spent an amazing amount of time perfecting this information and would like to know what the next step is to getting the info on the home page.  Please advise if there is anything I can do to assist in this process. Thanks!

**Comment by moottoast** [comment]
I'm going to merge this issue with #40.
