### ISSUE TITLE
DATES WRONG FOR COURSES

### ISSUE THREAD

**Issue by NovaG8r** [13gne/shcoderdojo#35]
The dates right under the MORE INFO/REGISTER boxes for each course are wrong.  Dates should be 4/3/17 - 5/8/17.  Someone wrote in that they were confused whether courses on Sunday or Monday as both were indicated.  I could not see how I can fix that part.  Please fix so I can or make changes asap. Both courses need to be fixed.
![capture](https://cloud.githubusercontent.com/assets/26885335/25095716/e519f896-236a-11e7-90e9-dbc61dddd5c6.JPG)

**Comment by moottoast** [comment]
Probably related to implementing the correct timezone. To fix, simply change the date of each of the course's associated sessions. The dates listed on the course#index page are the dates of the first and last sessions. So, if you update the dates of the sessions, it will change on the page you referenced.

**Comment by NovaG8r** [comment]
Thanks so much!  Fixed now!


Nancy

Nancy Vellucci
nvellucci@gmail.com
