### ISSUE TITLE
New homepage content

### ISSUE THREAD

**Issue by aaronstine** [13gne/shcoderdojo#40]
[Homepage Mockup.pdf](https://github.com/13gne/shcoderdojo/files/981105/Homepage.Mockup.pdf)
I've been working with Nancy on some additional content she wanted for the homepage. I put together a mockup so we could see what it looked like in context.

@moottoast Take a look at the attached mockup file and let me know what you think. Feel free to make any edits or go in a different UX direction. If you like any part of it, I can provide CSS and image assets.

**Comment by aaronstine** [comment]
@moottoast See attached for purchased art used in mockup.
[graphicriver-19676210-set-of-modern-flat-line-color-conceptual-icons.zip](https://github.com/13gne/shcoderdojo/files/986767/graphicriver-19676210-set-of-modern-flat-line-color-conceptual-icons.zip)

**Comment by moottoast** [comment]
Closing this issue since we moved the public facing stuff to Squarespace.
